//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AMP
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class MapEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto MapEntities1 usando la cadena de conexión encontrada en la sección 'MapEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public MapEntities1() : base("name=MapEntities1", "MapEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto MapEntities1.
        /// </summary>
        public MapEntities1(string connectionString) : base(connectionString, "MapEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto MapEntities1.
        /// </summary>
        public MapEntities1(EntityConnection connection) : base(connection, "MapEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Media> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Media>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Media> _Media;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Perfiles> Perfiles
        {
            get
            {
                if ((_Perfiles == null))
                {
                    _Perfiles = base.CreateObjectSet<Perfiles>("Perfiles");
                }
                return _Perfiles;
            }
        }
        private ObjectSet<Perfiles> _Perfiles;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Playlist> Playlist
        {
            get
            {
                if ((_Playlist == null))
                {
                    _Playlist = base.CreateObjectSet<Playlist>("Playlist");
                }
                return _Playlist;
            }
        }
        private ObjectSet<Playlist> _Playlist;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<normPlaylistsMedias> normPlaylistsMedias
        {
            get
            {
                if ((_normPlaylistsMedias == null))
                {
                    _normPlaylistsMedias = base.CreateObjectSet<normPlaylistsMedias>("normPlaylistsMedias");
                }
                return _normPlaylistsMedias;
            }
        }
        private ObjectSet<normPlaylistsMedias> _normPlaylistsMedias;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Player> Player
        {
            get
            {
                if ((_Player == null))
                {
                    _Player = base.CreateObjectSet<Player>("Player");
                }
                return _Player;
            }
        }
        private ObjectSet<Player> _Player;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Media. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMedia(Media media)
        {
            base.AddObject("Media", media);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Perfiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPerfiles(Perfiles perfiles)
        {
            base.AddObject("Perfiles", perfiles);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Playlist. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPlaylist(Playlist playlist)
        {
            base.AddObject("Playlist", playlist);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet normPlaylistsMedias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTonormPlaylistsMedias(normPlaylistsMedias normPlaylistsMedias)
        {
            base.AddObject("normPlaylistsMedias", normPlaylistsMedias);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Player. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPlayer(Player player)
        {
            base.AddObject("Player", player);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="idCliente">Valor inicial de la propiedad IdCliente.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad fechaCreacion.</param>
        /// <param name="fechaModificacion">Valor inicial de la propiedad fechaModificacion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Clientes CreateClientes(global::System.Int32 id, global::System.String idCliente, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.Int32 estado)
        {
            Clientes clientes = new Clientes();
            clientes.Id = id;
            clientes.IdCliente = idCliente;
            clientes.fechaCreacion = fechaCreacion;
            clientes.fechaModificacion = fechaModificacion;
            clientes.estado = estado;
            return clientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private global::System.String _IdCliente;
        partial void OnIdClienteChanging(global::System.String value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreCliente
        {
            get
            {
                return _nombreCliente;
            }
            set
            {
                OnnombreClienteChanging(value);
                ReportPropertyChanging("nombreCliente");
                _nombreCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombreCliente");
                OnnombreClienteChanged();
            }
        }
        private global::System.String _nombreCliente;
        partial void OnnombreClienteChanging(global::System.String value);
        partial void OnnombreClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaCreacion
        {
            get
            {
                return _fechaCreacion;
            }
            set
            {
                OnfechaCreacionChanging(value);
                ReportPropertyChanging("fechaCreacion");
                _fechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaCreacion");
                OnfechaCreacionChanged();
            }
        }
        private global::System.DateTime _fechaCreacion;
        partial void OnfechaCreacionChanging(global::System.DateTime value);
        partial void OnfechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaModificacion
        {
            get
            {
                return _fechaModificacion;
            }
            set
            {
                OnfechaModificacionChanging(value);
                ReportPropertyChanging("fechaModificacion");
                _fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaModificacion");
                OnfechaModificacionChanged();
            }
        }
        private global::System.DateTime _fechaModificacion;
        partial void OnfechaModificacionChanging(global::System.DateTime value);
        partial void OnfechaModificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creadoPor
        {
            get
            {
                return _creadoPor;
            }
            set
            {
                OncreadoPorChanging(value);
                ReportPropertyChanging("creadoPor");
                _creadoPor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creadoPor");
                OncreadoPorChanged();
            }
        }
        private global::System.String _creadoPor;
        partial void OncreadoPorChanging(global::System.String value);
        partial void OncreadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modificadoPor
        {
            get
            {
                return _modificadoPor;
            }
            set
            {
                OnmodificadoPorChanging(value);
                ReportPropertyChanging("modificadoPor");
                _modificadoPor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modificadoPor");
                OnmodificadoPorChanged();
            }
        }
        private global::System.String _modificadoPor;
        partial void OnmodificadoPorChanging(global::System.String value);
        partial void OnmodificadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Media")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Media : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Media.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad fechaCreacion.</param>
        /// <param name="fechaModificacion">Valor inicial de la propiedad fechaModificacion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="delete">Valor inicial de la propiedad delete.</param>
        public static Media CreateMedia(global::System.Int32 id, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.Int32 estado, global::System.Int32 delete)
        {
            Media media = new Media();
            media.id = id;
            media.fechaCreacion = fechaCreacion;
            media.fechaModificacion = fechaModificacion;
            media.estado = estado;
            media.delete = delete;
            return media;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idPlaylist
        {
            get
            {
                return _idPlaylist;
            }
            set
            {
                OnidPlaylistChanging(value);
                ReportPropertyChanging("idPlaylist");
                _idPlaylist = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idPlaylist");
                OnidPlaylistChanged();
            }
        }
        private global::System.String _idPlaylist;
        partial void OnidPlaylistChanging(global::System.String value);
        partial void OnidPlaylistChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ruta
        {
            get
            {
                return _ruta;
            }
            set
            {
                OnrutaChanging(value);
                ReportPropertyChanging("ruta");
                _ruta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ruta");
                OnrutaChanged();
            }
        }
        private global::System.String _ruta;
        partial void OnrutaChanging(global::System.String value);
        partial void OnrutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaCreacion
        {
            get
            {
                return _fechaCreacion;
            }
            set
            {
                OnfechaCreacionChanging(value);
                ReportPropertyChanging("fechaCreacion");
                _fechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaCreacion");
                OnfechaCreacionChanged();
            }
        }
        private global::System.DateTime _fechaCreacion;
        partial void OnfechaCreacionChanging(global::System.DateTime value);
        partial void OnfechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaModificacion
        {
            get
            {
                return _fechaModificacion;
            }
            set
            {
                OnfechaModificacionChanging(value);
                ReportPropertyChanging("fechaModificacion");
                _fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaModificacion");
                OnfechaModificacionChanged();
            }
        }
        private global::System.DateTime _fechaModificacion;
        partial void OnfechaModificacionChanging(global::System.DateTime value);
        partial void OnfechaModificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creadoPor
        {
            get
            {
                return _creadoPor;
            }
            set
            {
                OncreadoPorChanging(value);
                ReportPropertyChanging("creadoPor");
                _creadoPor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creadoPor");
                OncreadoPorChanged();
            }
        }
        private global::System.String _creadoPor;
        partial void OncreadoPorChanging(global::System.String value);
        partial void OncreadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modiificado
        {
            get
            {
                return _modiificado;
            }
            set
            {
                OnmodiificadoChanging(value);
                ReportPropertyChanging("modiificado");
                _modiificado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modiificado");
                OnmodiificadoChanged();
            }
        }
        private global::System.String _modiificado;
        partial void OnmodiificadoChanging(global::System.String value);
        partial void OnmodiificadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ext
        {
            get
            {
                return _ext;
            }
            set
            {
                OnextChanging(value);
                ReportPropertyChanging("ext");
                _ext = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ext");
                OnextChanged();
            }
        }
        private global::System.String _ext;
        partial void OnextChanging(global::System.String value);
        partial void OnextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fileOriginal
        {
            get
            {
                return _fileOriginal;
            }
            set
            {
                OnfileOriginalChanging(value);
                ReportPropertyChanging("fileOriginal");
                _fileOriginal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fileOriginal");
                OnfileOriginalChanged();
            }
        }
        private global::System.String _fileOriginal;
        partial void OnfileOriginalChanging(global::System.String value);
        partial void OnfileOriginalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 delete
        {
            get
            {
                return _delete;
            }
            set
            {
                OndeleteChanging(value);
                ReportPropertyChanging("delete");
                _delete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("delete");
                OndeleteChanged();
            }
        }
        private global::System.Int32 _delete;
        partial void OndeleteChanging(global::System.Int32 value);
        partial void OndeleteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="normPlaylistsMedias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class normPlaylistsMedias : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto normPlaylistsMedias.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="archivo">Valor inicial de la propiedad archivo.</param>
        /// <param name="idPlaylist">Valor inicial de la propiedad idPlaylist.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="idMedia">Valor inicial de la propiedad idMedia.</param>
        public static normPlaylistsMedias CreatenormPlaylistsMedias(global::System.Int32 id, global::System.String archivo, global::System.String idPlaylist, global::System.String nombre, global::System.Int32 idMedia)
        {
            normPlaylistsMedias normPlaylistsMedias = new normPlaylistsMedias();
            normPlaylistsMedias.id = id;
            normPlaylistsMedias.archivo = archivo;
            normPlaylistsMedias.idPlaylist = idPlaylist;
            normPlaylistsMedias.nombre = nombre;
            normPlaylistsMedias.idMedia = idMedia;
            return normPlaylistsMedias;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String archivo
        {
            get
            {
                return _archivo;
            }
            set
            {
                OnarchivoChanging(value);
                ReportPropertyChanging("archivo");
                _archivo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("archivo");
                OnarchivoChanged();
            }
        }
        private global::System.String _archivo;
        partial void OnarchivoChanging(global::System.String value);
        partial void OnarchivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idPlaylist
        {
            get
            {
                return _idPlaylist;
            }
            set
            {
                OnidPlaylistChanging(value);
                ReportPropertyChanging("idPlaylist");
                _idPlaylist = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idPlaylist");
                OnidPlaylistChanged();
            }
        }
        private global::System.String _idPlaylist;
        partial void OnidPlaylistChanging(global::System.String value);
        partial void OnidPlaylistChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMedia
        {
            get
            {
                return _idMedia;
            }
            set
            {
                OnidMediaChanging(value);
                ReportPropertyChanging("idMedia");
                _idMedia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idMedia");
                OnidMediaChanged();
            }
        }
        private global::System.Int32 _idMedia;
        partial void OnidMediaChanging(global::System.Int32 value);
        partial void OnidMediaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Perfiles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfiles : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Perfiles.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="perfil">Valor inicial de la propiedad perfil.</param>
        public static Perfiles CreatePerfiles(global::System.Int32 id, global::System.String perfil)
        {
            Perfiles perfiles = new Perfiles();
            perfiles.id = id;
            perfiles.perfil = perfil;
            return perfiles;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String perfil
        {
            get
            {
                return _perfil;
            }
            set
            {
                if (_perfil != value)
                {
                    OnperfilChanging(value);
                    ReportPropertyChanging("perfil");
                    _perfil = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("perfil");
                    OnperfilChanged();
                }
            }
        }
        private global::System.String _perfil;
        partial void OnperfilChanging(global::System.String value);
        partial void OnperfilChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Player.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad fechaCreacion.</param>
        /// <param name="fechaModificacion">Valor inicial de la propiedad fechaModificacion.</param>
        /// <param name="creadoPor">Valor inicial de la propiedad creadoPor.</param>
        /// <param name="modificadoPor">Valor inicial de la propiedad modificadoPor.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="actualizar">Valor inicial de la propiedad actualizar.</param>
        public static Player CreatePlayer(global::System.Int32 id, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.String creadoPor, global::System.String modificadoPor, global::System.Int32 estado, global::System.Int32 actualizar)
        {
            Player player = new Player();
            player.id = id;
            player.fechaCreacion = fechaCreacion;
            player.fechaModificacion = fechaModificacion;
            player.creadoPor = creadoPor;
            player.modificadoPor = modificadoPor;
            player.estado = estado;
            player.actualizar = actualizar;
            return player;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idPlayer
        {
            get
            {
                return _idPlayer;
            }
            set
            {
                OnidPlayerChanging(value);
                ReportPropertyChanging("idPlayer");
                _idPlayer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idPlayer");
                OnidPlayerChanged();
            }
        }
        private global::System.String _idPlayer;
        partial void OnidPlayerChanging(global::System.String value);
        partial void OnidPlayerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private global::System.String _idCliente;
        partial void OnidClienteChanging(global::System.String value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String uID
        {
            get
            {
                return _uID;
            }
            set
            {
                OnuIDChanging(value);
                ReportPropertyChanging("uID");
                _uID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("uID");
                OnuIDChanged();
            }
        }
        private global::System.String _uID;
        partial void OnuIDChanging(global::System.String value);
        partial void OnuIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sucursal
        {
            get
            {
                return _sucursal;
            }
            set
            {
                OnsucursalChanging(value);
                ReportPropertyChanging("sucursal");
                _sucursal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sucursal");
                OnsucursalChanged();
            }
        }
        private global::System.String _sucursal;
        partial void OnsucursalChanging(global::System.String value);
        partial void OnsucursalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaCreacion
        {
            get
            {
                return _fechaCreacion;
            }
            set
            {
                OnfechaCreacionChanging(value);
                ReportPropertyChanging("fechaCreacion");
                _fechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaCreacion");
                OnfechaCreacionChanged();
            }
        }
        private global::System.DateTime _fechaCreacion;
        partial void OnfechaCreacionChanging(global::System.DateTime value);
        partial void OnfechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaModificacion
        {
            get
            {
                return _fechaModificacion;
            }
            set
            {
                OnfechaModificacionChanging(value);
                ReportPropertyChanging("fechaModificacion");
                _fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaModificacion");
                OnfechaModificacionChanged();
            }
        }
        private global::System.DateTime _fechaModificacion;
        partial void OnfechaModificacionChanging(global::System.DateTime value);
        partial void OnfechaModificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String creadoPor
        {
            get
            {
                return _creadoPor;
            }
            set
            {
                OncreadoPorChanging(value);
                ReportPropertyChanging("creadoPor");
                _creadoPor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("creadoPor");
                OncreadoPorChanged();
            }
        }
        private global::System.String _creadoPor;
        partial void OncreadoPorChanging(global::System.String value);
        partial void OncreadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modificadoPor
        {
            get
            {
                return _modificadoPor;
            }
            set
            {
                OnmodificadoPorChanging(value);
                ReportPropertyChanging("modificadoPor");
                _modificadoPor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("modificadoPor");
                OnmodificadoPorChanged();
            }
        }
        private global::System.String _modificadoPor;
        partial void OnmodificadoPorChanging(global::System.String value);
        partial void OnmodificadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idPlaylist
        {
            get
            {
                return _idPlaylist;
            }
            set
            {
                OnidPlaylistChanging(value);
                ReportPropertyChanging("idPlaylist");
                _idPlaylist = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idPlaylist");
                OnidPlaylistChanged();
            }
        }
        private global::System.String _idPlaylist;
        partial void OnidPlaylistChanging(global::System.String value);
        partial void OnidPlaylistChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String uPlayer
        {
            get
            {
                return _uPlayer;
            }
            set
            {
                OnuPlayerChanging(value);
                ReportPropertyChanging("uPlayer");
                _uPlayer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("uPlayer");
                OnuPlayerChanged();
            }
        }
        private global::System.String _uPlayer;
        partial void OnuPlayerChanging(global::System.String value);
        partial void OnuPlayerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sonido
        {
            get
            {
                return _sonido;
            }
            set
            {
                OnsonidoChanging(value);
                ReportPropertyChanging("sonido");
                _sonido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sonido");
                OnsonidoChanged();
            }
        }
        private global::System.String _sonido;
        partial void OnsonidoChanging(global::System.String value);
        partial void OnsonidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 actualizar
        {
            get
            {
                return _actualizar;
            }
            set
            {
                OnactualizarChanging(value);
                ReportPropertyChanging("actualizar");
                _actualizar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("actualizar");
                OnactualizarChanged();
            }
        }
        private global::System.Int32 _actualizar;
        partial void OnactualizarChanging(global::System.Int32 value);
        partial void OnactualizarChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Playlist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Playlist : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Playlist.
        /// </summary>
        /// <param name="gen">Valor inicial de la propiedad Gen.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad fechaCreacion.</param>
        /// <param name="fechaModificacion">Valor inicial de la propiedad fechaModificacion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Playlist CreatePlaylist(global::System.Int32 gen, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.Int32 estado)
        {
            Playlist playlist = new Playlist();
            playlist.Gen = gen;
            playlist.fechaCreacion = fechaCreacion;
            playlist.fechaModificacion = fechaModificacion;
            playlist.estado = estado;
            return playlist;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gen
        {
            get
            {
                return _Gen;
            }
            set
            {
                if (_Gen != value)
                {
                    OnGenChanging(value);
                    ReportPropertyChanging("Gen");
                    _Gen = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Gen");
                    OnGenChanged();
                }
            }
        }
        private global::System.Int32 _Gen;
        partial void OnGenChanging(global::System.Int32 value);
        partial void OnGenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idPlaylist
        {
            get
            {
                return _idPlaylist;
            }
            set
            {
                OnidPlaylistChanging(value);
                ReportPropertyChanging("idPlaylist");
                _idPlaylist = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idPlaylist");
                OnidPlaylistChanged();
            }
        }
        private global::System.String _idPlaylist;
        partial void OnidPlaylistChanging(global::System.String value);
        partial void OnidPlaylistChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaCreacion
        {
            get
            {
                return _fechaCreacion;
            }
            set
            {
                OnfechaCreacionChanging(value);
                ReportPropertyChanging("fechaCreacion");
                _fechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaCreacion");
                OnfechaCreacionChanged();
            }
        }
        private global::System.DateTime _fechaCreacion;
        partial void OnfechaCreacionChanging(global::System.DateTime value);
        partial void OnfechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaModificacion
        {
            get
            {
                return _fechaModificacion;
            }
            set
            {
                OnfechaModificacionChanging(value);
                ReportPropertyChanging("fechaModificacion");
                _fechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaModificacion");
                OnfechaModificacionChanged();
            }
        }
        private global::System.DateTime _fechaModificacion;
        partial void OnfechaModificacionChanging(global::System.DateTime value);
        partial void OnfechaModificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String creadoPor
        {
            get
            {
                return _creadoPor;
            }
            set
            {
                OncreadoPorChanging(value);
                ReportPropertyChanging("creadoPor");
                _creadoPor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("creadoPor");
                OncreadoPorChanged();
            }
        }
        private global::System.String _creadoPor;
        partial void OncreadoPorChanging(global::System.String value);
        partial void OncreadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modificadoPor
        {
            get
            {
                return _modificadoPor;
            }
            set
            {
                OnmodificadoPorChanging(value);
                ReportPropertyChanging("modificadoPor");
                _modificadoPor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modificadoPor");
                OnmodificadoPorChanged();
            }
        }
        private global::System.String _modificadoPor;
        partial void OnmodificadoPorChanging(global::System.String value);
        partial void OnmodificadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MapModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuarios.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="idUsuario">Valor inicial de la propiedad idUsuario.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="idPerfil">Valor inicial de la propiedad idPerfil.</param>
        /// <param name="idCliente">Valor inicial de la propiedad idCliente.</param>
        /// <param name="creadoPor">Valor inicial de la propiedad creadoPor.</param>
        /// <param name="modificadoPor">Valor inicial de la propiedad modificadoPor.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad fechaCreacion.</param>
        /// <param name="fechaModificacion">Valor inicial de la propiedad fechaModificacion.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 id, global::System.String idUsuario, global::System.String usuario, global::System.String contrasena, global::System.Int32 idPerfil, global::System.String idCliente, global::System.String creadoPor, global::System.String modificadoPor, global::System.DateTime fechaCreacion, global::System.DateTime fechaModificacion, global::System.Int32 estado)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.id = id;
            usuarios.idUsuario = idUsuario;
            usuarios.usuario = usuario;
            usuarios.contrasena = contrasena;
            usuarios.idPerfil = idPerfil;
            usuarios.idCliente = idCliente;
            usuarios.creadoPor = creadoPor;
            usuarios.modificadoPor = modificadoPor;
            usuarios.fechaCreacion = fechaCreacion;
            usuarios.fechaModificacion = fechaModificacion;
            usuarios.estado = estado;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idUsuario
        {
            get
            {
                return _idUsuario;
            }
            set
            {
                if (_idUsuario != value)
                {
                    OnidUsuarioChanging(value);
                    ReportPropertyChanging("idUsuario");
                    _idUsuario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idUsuario");
                    OnidUsuarioChanged();
                }
            }
        }
        private global::System.String _idUsuario;
        partial void OnidUsuarioChanging(global::System.String value);
        partial void OnidUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                if (_usuario != value)
                {
                    OnusuarioChanging(value);
                    ReportPropertyChanging("usuario");
                    _usuario = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("usuario");
                    OnusuarioChanged();
                }
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                if (_contrasena != value)
                {
                    OncontrasenaChanging(value);
                    ReportPropertyChanging("contrasena");
                    _contrasena = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("contrasena");
                    OncontrasenaChanged();
                }
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPerfil
        {
            get
            {
                return _idPerfil;
            }
            set
            {
                if (_idPerfil != value)
                {
                    OnidPerfilChanging(value);
                    ReportPropertyChanging("idPerfil");
                    _idPerfil = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPerfil");
                    OnidPerfilChanged();
                }
            }
        }
        private global::System.Int32 _idPerfil;
        partial void OnidPerfilChanging(global::System.Int32 value);
        partial void OnidPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                if (_idCliente != value)
                {
                    OnidClienteChanging(value);
                    ReportPropertyChanging("idCliente");
                    _idCliente = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idCliente");
                    OnidClienteChanged();
                }
            }
        }
        private global::System.String _idCliente;
        partial void OnidClienteChanging(global::System.String value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String creadoPor
        {
            get
            {
                return _creadoPor;
            }
            set
            {
                if (_creadoPor != value)
                {
                    OncreadoPorChanging(value);
                    ReportPropertyChanging("creadoPor");
                    _creadoPor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("creadoPor");
                    OncreadoPorChanged();
                }
            }
        }
        private global::System.String _creadoPor;
        partial void OncreadoPorChanging(global::System.String value);
        partial void OncreadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modificadoPor
        {
            get
            {
                return _modificadoPor;
            }
            set
            {
                if (_modificadoPor != value)
                {
                    OnmodificadoPorChanging(value);
                    ReportPropertyChanging("modificadoPor");
                    _modificadoPor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("modificadoPor");
                    OnmodificadoPorChanged();
                }
            }
        }
        private global::System.String _modificadoPor;
        partial void OnmodificadoPorChanging(global::System.String value);
        partial void OnmodificadoPorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaCreacion
        {
            get
            {
                return _fechaCreacion;
            }
            set
            {
                if (_fechaCreacion != value)
                {
                    OnfechaCreacionChanging(value);
                    ReportPropertyChanging("fechaCreacion");
                    _fechaCreacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fechaCreacion");
                    OnfechaCreacionChanged();
                }
            }
        }
        private global::System.DateTime _fechaCreacion;
        partial void OnfechaCreacionChanging(global::System.DateTime value);
        partial void OnfechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaModificacion
        {
            get
            {
                return _fechaModificacion;
            }
            set
            {
                if (_fechaModificacion != value)
                {
                    OnfechaModificacionChanging(value);
                    ReportPropertyChanging("fechaModificacion");
                    _fechaModificacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fechaModificacion");
                    OnfechaModificacionChanged();
                }
            }
        }
        private global::System.DateTime _fechaModificacion;
        partial void OnfechaModificacionChanging(global::System.DateTime value);
        partial void OnfechaModificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                if (_estado != value)
                {
                    OnestadoChanging(value);
                    ReportPropertyChanging("estado");
                    _estado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("estado");
                    OnestadoChanged();
                }
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
    }

    #endregion

    
}
